name: autorun-pm2

on:
  workflow_dispatch:
  schedule:
    # 5分钟运行一次
    - cron: '0/10 * * * *'
  push:
    branches:
      - main
    paths:
      - ".github/pm2.yml"

jobs:
  ssh-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Check if service is running
      id: check_service
      run: |
        if curl --head --silent --fail https://status.sharkbee.us.kg > /dev/null; then #这里改成你的Web服务的地址
          echo "service_status=running" >> $GITHUB_ENV
        else
          echo "service_status=not_running" >> $GITHUB_ENV
        fi

    - name: Run script on remote server if service is not running
      if: env.service_status == 'not_running'
      run: |
        # Set up SSH agent and load private key
        echo "${{ secrets.SSH_PRIVATE_KEY }}" | ssh-agent sh -c 'ssh-add /dev/stdin; ssh -o StrictHostKeyChecking=no sharkbee@s2.serv00.com "/home/sharkbee/run.sh"'
