name: Serv00 Regist Script

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "* */24 * * *"  # 每24小时运行一次，可以根据需求调整时间
  push:
    branches:
      - main
    paths:
      - ".github/reg.yml"
       
jobs:
  regist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 仓库代码
        uses: actions/checkout@v2

      - name: 设置 Python 环境
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # 设置你希望使用的 Python 版本，建议使用稳定版本

      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install ddddocr loguru requests

      - name: 运行注册脚本
        env:
          Email: ${{ secrets.Email }}
        run: |
          python reg.py
